### ISSUE TITLE
Watch for script changes

### ISSUE THREAD

**Issue by neico** [tvandijck/PremakeExtension#3]
I was playing with the thought of making a VS extension quite a while ago with it's sole purpose of watching the premake script (and maybe it's included sub-scripts) and automatically re-run premake upon change.

But since this extension exists now I'll just head over to request it here.

I assume the `FileSystemWatcher` class would play a big role in this.

might be actually related to #1 I guess

**Comment by tvandijck** [comment]
I don't think this is a good idea. Visual Studio doesn't really behave nicely when a vcxproj/sln changes, since it completely unloads/reloads it, closing all files part of that project in its wake.. So I'd rather keep this explicit, when I ask for it.

That said, in VS2017 they did add the ability to use cmake directly, and there is seems to somewhat work dynamically... maybe we can build something similar for premake.
